import type { DocumentationAnalysis, DocumentationSection } from "@/services/analysisApi"

function SectionCard({ label, section, color }: { label: string; section: DocumentationSection; color: string }) {
  return <div className="rounded-xl p-4 bg-[#0e0e1a] border border-white/[0.06]"><div className="flex items-center justify-between"><span className="text-xs text-gray-400">{label}</span><span className="font-mono text-lg font-bold" style={{ color }}>{section.coverage == null ? "N/A" : `${section.coverage}%`}</span></div><div className="text-xs text-gray-600 mt-1">{section.documented} documented / {section.total} total</div>{section.coverage != null && <div className="mt-3 h-1.5 bg-white/10 rounded-full"><div className="h-full rounded-full" style={{ width: `${section.coverage}%`, backgroundColor: color }} /></div>}</div>
}

export default function DocumentationPanel({ analysis }: { analysis: DocumentationAnalysis | null }) {
  if (!analysis) return <div className="rounded-xl border border-white/[0.06] bg-[#0e0e1a] p-6 text-center text-sm text-gray-500">Documentation analysis is not available from the current analysis.</div>
  const coverages = [analysis.functions.coverage, analysis.classes.coverage, analysis.methods.coverage].filter((value): value is number => value != null)
  const overall = coverages.length ? Math.round(coverages.reduce((sum, value) => sum + value, 0) / coverages.length) : null
  return <div className="space-y-5"><div className="text-xs text-gray-500">Documentation quality indicators derived from repository structure and analyzed source.</div><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><div className="rounded-xl p-4 bg-[#0e0e1a] border border-white/[0.06]"><div className="text-xs text-gray-500">AST Coverage</div><div className="font-mono text-xl font-bold text-violet-300 mt-1">{analysis.ast_files} / {analysis.source_files}</div><div className="text-xs text-gray-600 mt-1">{analysis.ast_coverage_percent == null ? "Not available" : `${analysis.ast_coverage_percent}% of source files analyzed`}</div></div><div className="rounded-xl p-4 bg-[#0e0e1a] border border-white/[0.06]"><div className="text-xs text-gray-500">README</div><div className="font-mono text-xl font-bold text-violet-300 mt-1">{analysis.readme.exists ? "Present" : "Missing"}</div><div className="text-xs text-gray-600 mt-1">{analysis.readme.lines == null ? "Content size unavailable" : `${analysis.readme.lines} lines · ${analysis.readme.word_count} words`}</div></div><div className="rounded-xl p-4 bg-[#0e0e1a] border border-white/[0.06]"><div className="text-xs text-gray-500">Documentation Files</div><div className="font-mono text-xl font-bold text-cyan-300 mt-1">{analysis.documentation_files}</div><div className="text-xs text-gray-600 mt-1">Markdown, RST, and docs paths</div></div></div><div className="text-xs text-gray-600">Function, class, and method coverage below is calculated from AST-analyzed files only. Overall: {overall == null ? "N/A" : `${overall}% of analyzed entities`}</div><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><SectionCard label="Function Documentation" section={analysis.functions} color="#8b5cf6" /><SectionCard label="Class Documentation" section={analysis.classes} color="#06b6d4" /><SectionCard label="Method Documentation" section={analysis.methods} color="#34d399" /></div><div className="rounded-xl p-4 bg-[#0e0e1a] border border-white/[0.06]"><div className="font-mono text-xs text-gray-500 uppercase tracking-widest mb-3">Maintenance Indicators</div><div className="grid grid-cols-3 gap-3 text-center"><div><div className="font-mono text-xl font-bold text-yellow-300">{analysis.todo_count}</div><div className="text-xs text-gray-600">TODO</div></div><div><div className="font-mono text-xl font-bold text-orange-300">{analysis.fixme_count}</div><div className="text-xs text-gray-600">FIXME</div></div><div><div className="font-mono text-xl font-bold text-gray-300">{analysis.source_comment_lines}</div><div className="text-xs text-gray-600">comment lines</div></div></div></div></div>
}
